// Ported from SubtitleEdit: SubStationAlpha.cs + AdvancedSubStationAlpha.cs
import '../core/paragraph.dart';
import '../core/subtitle.dart';
import '../core/subtitle_format.dart';
import '../core/time_code.dart';

class SubStationAlpha extends SubtitleFormat {
  final bool advanced;
  SubStationAlpha({this.advanced = false});

  @override
  String get name =>
      advanced ? 'Advanced Sub Station Alpha' : 'Sub Station Alpha';
  @override
  String get extension => advanced ? '.ass' : '.ssa';

  static const _defaultHeaderAss = '''[Script Info]
; Generated by Subtitle Sync
ScriptType: v4.00+

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
''';

  @override
  bool isMine(List<String> lines, String fileName) {
    final joined = lines.take(40).join('\n');
    if (!joined.contains('[Script Info]')) return false;
    if (advanced) {
      return joined.contains('v4.00+') ||
          joined.contains('[V4+ Styles]') ||
          fileName.toLowerCase().endsWith('.ass');
    }
    return !joined.contains('v4.00+') || fileName.toLowerCase().endsWith('.ssa');
  }

  @override
  void loadSubtitle(Subtitle subtitle, List<String> lines, String fileName) {
    subtitle.paragraphs.clear();
    final headerBuf = StringBuffer();
    var inEvents = false;
    List<String>? eventFormat;

    for (var raw in lines) {
      final line = raw.replaceAll('\uFEFF', '').trimRight();
      if (line.toLowerCase().startsWith('[events]')) {
        inEvents = true;
        headerBuf.writeln(line);
        continue;
      }
      if (!inEvents) {
        headerBuf.writeln(line);
        continue;
      }
      if (line.toLowerCase().startsWith('format:')) {
        eventFormat = line
            .substring(7)
            .split(',')
            .map((s) => s.trim().toLowerCase())
            .toList();
        headerBuf.writeln(line);
        continue;
      }
      final lower = line.toLowerCase();
      final isDialogue = lower.startsWith('dialogue:');
      final isComment = lower.startsWith('comment:');
      if (!isDialogue && !isComment) continue;
      if (eventFormat == null) continue;

      final colonIdx = line.indexOf(':');
      final payload = line.substring(colonIdx + 1).trimLeft();
      final parts = _splitWithMaxText(payload, eventFormat.length);
      final p = Paragraph(isComment: isComment);
      for (var i = 0; i < eventFormat.length && i < parts.length; i++) {
        final key = eventFormat[i];
        final val = parts[i];
        switch (key) {
          case 'start':
            p.startTime = _parseAssTime(val);
            break;
          case 'end':
            p.endTime = _parseAssTime(val);
            break;
          case 'style':
            p.style = val;
            break;
          case 'name':
          case 'actor':
            p.actor = val;
            break;
          case 'effect':
            p.effect = val;
            break;
          case 'marginl':
            p.marginL = int.tryParse(val) ?? 0;
            break;
          case 'marginr':
            p.marginR = int.tryParse(val) ?? 0;
            break;
          case 'marginv':
            p.marginV = int.tryParse(val) ?? 0;
            break;
          case 'layer':
            p.layer = int.tryParse(val) ?? 0;
            break;
          case 'text':
            p.text = val.replaceAll(r'\N', '\n').replaceAll(r'\n', '\n');
            break;
        }
      }
      if (p.endTime.totalMilliseconds > 0) subtitle.paragraphs.add(p);
    }
    subtitle.header = headerBuf.toString();
    subtitle.renumber();
  }

  List<String> _splitWithMaxText(String s, int fieldCount) {
    final result = <String>[];
    var idx = 0;
    for (var i = 0; i < fieldCount - 1; i++) {
      final c = s.indexOf(',', idx);
      if (c == -1) {
        result.add(s.substring(idx));
        return result;
      }
      result.add(s.substring(idx, c));
      idx = c + 1;
    }
    result.add(s.substring(idx));
    return result;
  }

  TimeCode _parseAssTime(String s) {
    final parts = s.split(RegExp(r'[:.]'));
    if (parts.length < 4) return TimeCode();
    return TimeCode.fromHms(
      int.tryParse(parts[0]) ?? 0,
      int.tryParse(parts[1]) ?? 0,
      int.tryParse(parts[2]) ?? 0,
      (int.tryParse(parts[3]) ?? 0) * 10,
    );
  }

  @override
  String toText(Subtitle subtitle, String title) {
    final hasHeader = subtitle.header.isNotEmpty &&
        subtitle.header.contains(advanced ? '[V4+ Styles]' : '[V4 Styles]');
    final sb = StringBuffer();
    if (hasHeader) {
      sb.write(subtitle.header.trimRight());
      sb.writeln();
    } else {
      sb.write(_defaultHeaderAss);
    }
    for (final p in subtitle.paragraphs) {
      final text = p.text.replaceAll('\n', r'\N');
      sb.writeln(
          '${p.isComment ? 'Comment' : 'Dialogue'}: ${p.layer},${p.startTime.toAss()},${p.endTime.toAss()},${p.style},${p.actor},${p.marginL.toString().padLeft(4, '0')},${p.marginR.toString().padLeft(4, '0')},${p.marginV.toString().padLeft(4, '0')},${p.effect},$text');
    }
    return sb.toString();
  }
}

class AdvancedSubStationAlpha extends SubStationAlpha {
  AdvancedSubStationAlpha() : super(advanced: true);
}
